# Change these first
owner: neumatic-bot # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

commitMessages:
  commitAuthorName: "neumatic-bot"
  commitAuthorEmail: "neumatic@seized.email"
workflowSchedule:
  graphs: "*/10 * * * *"
  responseTime: "*/10 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/10 * * * *"
  updateTemplate: "*/10 * * * *"
  updates: "*/10 * * * *"
  uptime: "*/10 * * * *"
sites:
  - name: Neumatic.ML
    url: https://neumatic.ml
  - name: Forum.Neumatic.ML
    url: https://forum.neumatic.ml
  - name: CDN.Neumatic.ML
    url: https://cdn.neumatic.ml
  - name: Finn SMP
    url: https://finnsmp.ml
  - name: Pip SMP
    url: http://www.pipsmp.ml

status-website:
  theme: dark

  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.neumatic.ml
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/77523929?s=400&u=c4365e03b1309e818a2c7e671254755b8b98716e&v=4
  name: Status.neumatic.ml
  introTitle: "Welcome to Neumatic Status!"
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
